name: CI-CD

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Criando a imagem Docker
        uses: docker/build-push-action@v2.3.0
        with:
          context: ./src
          file: ./src/Dockerfile
          tags: |
            wzuqui/api-produto:latest
            wzuqui/api-produto:${{ github.run_number }}
          push: true
